// Popular emojis organized by category
export const emojiCategories = {
  "Smileys & People": [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "😂",
    "🤣",
    "😊",
    "😇",
    "🙂",
    "🙃",
    "😉",
    "😌",
    "😍",
    "🥰",
    "😘",
    "😗",
    "😙",
    "😚",
    "😋",
    "😛",
    "😝",
    "😜",
    "🤪",
    "🤨",
    "🧐",
    "🤓",
    "😎",
    "🤩",
    "🥳",
    "😏",
    "😒",
    "😞",
    "😔",
    "😟",
    "😕",
    "🙁",
    "☹️",
    "😣",
    "😖",
    "😫",
    "😩",
    "🥺",
    "😢",
    "😭",
    "😤",
    "😠",
    "😡",
    "🤬",
    "🤯",
    "😳",
    "🥵",
    "🥶",
    "😱",
    "😨",
    "😰",
    "😥",
    "😓",
    "🤗",
    "🤔",
    "🤭",
    "🤫",
    "🤥",
    "😶",
    "😐",
    "😑",
    "😬",
    "🙄",
    "😯",
    "😦",
    "😧",
    "😮",
    "😲",
    "🥱",
    "😴",
    "🤤",
    "😪",
    "😵",
    "🤐",
    "🥴",
    "🤢",
    "🤮",
    "🤧",
    "😷",
    "🤒",
    "🤕",
    "🤑",
    "🤠",
    "😈",
    "👿",
    "👹",
    "👺",
    "🤡",
    "💩",
    "👻",
    "💀",
    "☠️",
    "👽",
    "👾",
    "🤖",
    "🎃",
    "😺",
    "😸",
    "😹",
    "😻",
    "😼",
    "😽",
    "🙀",
    "😿",
    "😾",
    "👶",
    "👧",
    "🧒",
    "👦",
    "👩",
    "🧑",
    "👨",
    "👵",
    "🧓",
    "👴",
    "👮",
    "👷",
    "💂",
    "🕵️",
    "👰",
    "🤵",
    "👸",
    "🤴",
    "🦸",
    "🦹",
    "🧙",
    "🧚",
    "🧛",
    "🧜",
    "🧝",
    "🧞",
    "🧟",
    "💆",
    "💇",
    "🚶",
    "🏃",
    "💃",
    "🕺",
    "🕴️",
    "👯",
    "🧘",
    "🧗",
    "🤺",
    "🏇",
    "⛷️",
    "🏂",
    "🏌️",
    "🏄",
    "🚣",
    "🏊",
    "⛹️",
    "🏋️",
    "🚴",
    "🚵",
    "🤸",
    "🤼",
    "🤽",
    "🤾",
    "🤹",
    "🛀",
    "🛌",
    "👭",
    "👫",
    "👬",
    "💏",
    "💑",
    "👪",
    "👀",
    "👁️",
    "👅",
    "👄",
    "💋",
    "🩸",
  ],
  "Animals & Nature": [
    "🐶",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🦊",
    "🐻",
    "🐼",
    "🐨",
    "🐯",
    "🦁",
    "🐮",
    "🐷",
    "🐽",
    "🐸",
    "🐵",
    "🙈",
    "🙉",
    "🙊",
    "🐒",
    "🐔",
    "🐧",
    "🐦",
    "🐤",
    "🐣",
    "🐥",
    "🦆",
    "🦅",
    "🦉",
    "🦇",
    "🐺",
    "🐗",
    "🐴",
    "🦄",
    "🐝",
    "🐛",
    "🦋",
    "🐌",
    "🐞",
    "🐜",
    "🦟",
    "🦗",
    "🕷️",
    "🦂",
    "🐢",
    "🐍",
    "🦎",
    "🦖",
    "🦕",
    "🐙",
    "🦑",
    "🦐",
    "🦞",
    "🦀",
    "🐡",
    "🐠",
    "🐟",
    "🐬",
    "🐳",
    "🐋",
    "🦈",
    "🐊",
    "🐅",
    "🐆",
    "🦓",
    "🦍",
    "🦧",
    "🐘",
    "🦛",
    "🦏",
    "🐪",
    "🐫",
    "🦒",
    "🦘",
    "🦡",
    "🐃",
    "🐂",
    "🐄",
    "🐎",
    "🐖",
    "🐏",
    "🐑",
    "🦙",
    "🐐",
    "🦌",
    "🐕",
    "🐩",
    "🐈",
    "🐓",
    "🦃",
    "🌵",
    "🎄",
    "🌲",
    "🌳",
    "🌴",
    "🌱",
    "🌿",
    "☘️",
    "🍀",
    "🎍",
    "🎋",
    "🍃",
    "🍂",
    "🍁",
    "🍄",
    "🌾",
    "💐",
    "🌷",
    "🌹",
    "🥀",
    "🌺",
    "🌸",
    "🌼",
    "🌻",
    "🌞",
    "🌝",
    "🌛",
    "🌜",
    "🌚",
    "🌕",
    "🌖",
    "🌗",
    "🌘",
    "🌑",
    "🌒",
    "🌓",
    "🌔",
    "🌙",
    "🌎",
    "🌍",
    "🌏",
    "💫",
    "⭐",
    "🌟",
    "✨",
    "⚡",
    "☄️",
    "💥",
    "🔥",
    "☀️",
    "🌤️",
    "⛅",
    "🌥️",
    "☁️",
    "🌦️",
    "🌧️",
    "⛈️",
    "🌩️",
    "🌨️",
    "❄️",
    "☃️",
    "⛄",
    "🌬️",
    "💨",
    "💧",
    "💦",
    "☔",
    "☂️",
    "🌊",
    "🌫️",
  ],
  "Food & Drink": [
    "🍏",
    "🍎",
    "🍐",
    "🍊",
    "🍋",
    "🍌",
    "🍉",
    "🍇",
    "🍓",
    "🍈",
    "🍒",
    "🍑",
    "🥭",
    "🍍",
    "🥥",
    "🥝",
    "🍅",
    "🍆",
    "🥑",
    "🥦",
    "🥬",
    "🥒",
    "🌶️",
    "🌽",
    "🥕",
    "🥔",
    "🍠",
    "🥐",
    "🥯",
    "🍞",
    "🥖",
    "🥨",
    "🧀",
    "🥚",
    "🍳",
    "🥞",
    "🥓",
    "🥩",
    "🍗",
    "🍖",
    "🦴",
    "🌭",
    "🍔",
    "🍟",
    "🍕",
    "🥪",
    "🥙",
    "🌮",
    "🌯",
    "🥗",
    "🥘",
    "🥫",
    "🍝",
    "🍜",
    "🍲",
    "🍛",
    "🍣",
    "🍱",
    "🥟",
    "🍤",
    "🍙",
    "🍚",
    "🍘",
    "🍥",
    "🥠",
    "🍢",
    "🍡",
    "🍧",
    "🍨",
    "🍦",
    "🥧",
    "🍰",
    "🎂",
    "🍮",
    "🍭",
    "🍬",
    "🍫",
    "🍿",
    "🍩",
    "🍪",
    "🌰",
    "🥜",
    "🍯",
    "🥛",
    "🍼",
    "☕",
    "🍵",
    "🥤",
    "🍶",
    "🍺",
    "🍻",
    "🥂",
    "🍷",
    "🥃",
    "🍸",
    "🍹",
    "🧃",
    "🧉",
    "🧊",
    "🥄",
    "🍴",
    "🍽️",
    "🥣",
    "🥡",
    "🥢",
    "🧂",
  ],
  "Activity & Sports": [
    "⚽",
    "🏀",
    "🏈",
    "⚾",
    "🥎",
    "🎾",
    "🏐",
    "🏉",
    "🥏",
    "🎱",
    "🏓",
    "🏸",
    "🥅",
    "🏒",
    "🏑",
    "🏏",
    "🥍",
    "🏹",
    "🎣",
    "🥊",
    "🥋",
    "🎽",
    "🛹",
    "🛷",
    "⛸️",
    "🥌",
    "🎿",
    "⛷️",
    "🏂",
    "🏋️",
    "🤼",
    "🤸",
    "🤺",
    "⛹️",
    "🤾",
    "🏌️",
    "🏇",
    "🧘",
    "🏄",
    "🏊",
    "🚣",
    "🧗",
    "🚵",
    "🚴",
    "🏆",
    "🥇",
    "🥈",
    "🥉",
    "🏅",
    "🎖️",
    "🏵️",
    "🎗️",
    "🎫",
    "🎟️",
    "🎪",
    "🤹",
    "🎭",
    "🩰",
    "🎨",
    "🎬",
    "🎤",
    "🎧",
    "🎼",
    "🎹",
    "🥁",
    "🎷",
    "🎺",
    "🎸",
    "🎻",
    "🎲",
    "♟️",
    "🎯",
    "🎳",
    "🎮",
    "🎰",
    "🧩",
  ],
  "Travel & Places": [
    "🚗",
    "🚕",
    "🚙",
    "🚌",
    "🚎",
    "🏎️",
    "🚓",
    "🚑",
    "🚒",
    "🚐",
    "🚚",
    "🚛",
    "🚜",
    "🛴",
    "🚲",
    "🛵",
    "🏍️",
    "🛺",
    "🚨",
    "🚔",
    "🚍",
    "🚘",
    "🚖",
    "🚡",
    "🚠",
    "🚟",
    "🚃",
    "🚋",
    "🚞",
    "🚝",
    "🚄",
    "🚅",
    "🚈",
    "🚂",
    "🚆",
    "🚇",
    "🚊",
    "🚉",
    "✈️",
    "🛫",
    "🛬",
    "🛩️",
    "💺",
    "🚀",
    "🛸",
    "🚁",
    "🛶",
    "⛵",
    "🚤",
    "🛥️",
    "🛳️",
    "⛴️",
    "🚢",
    "⚓",
    "⛽",
    "🚧",
    "🚦",
    "🚥",
    "🗺️",
    "🗿",
    "🗽",
    "🗼",
    "🏰",
    "🏯",
    "🏟️",
    "🎡",
    "🎢",
    "🎠",
    "⛲",
    "⛱️",
    "🏖️",
    "🏝️",
    "🏜️",
    "🌋",
    "⛰️",
    "🏔️",
    "🗻",
    "🏕️",
    "⛺",
    "🏠",
    "🏡",
    "🏘️",
    "🏚️",
    "🏗️",
    "🏭",
    "🏢",
    "🏬",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏪",
    "🏫",
    "🏩",
    "💒",
    "🏛️",
    "⛪",
    "🕌",
    "🕍",
    "🕋",
    "⛩️",
    "🛤️",
    "🛣️",
    "🗾",
    "🎑",
    "🏞️",
    "🌅",
    "🌄",
    "🌠",
    "🎇",
    "🎆",
    "🌇",
    "🌆",
    "🏙️",
    "🌃",
    "🌌",
    "🌉",
    "🌁",
  ],
  Objects: [
    "⌚",
    "📱",
    "📲",
    "💻",
    "⌨️",
    "🖥️",
    "🖨️",
    "🖱️",
    "🖲️",
    "🕹️",
    "🗜️",
    "💾",
    "💿",
    "📀",
    "📼",
    "📷",
    "📸",
    "📹",
    "🎥",
    "📽️",
    "🎞️",
    "📞",
    "☎️",
    "📟",
    "📠",
    "📺",
    "📻",
    "🎙️",
    "🎚️",
    "🎛️",
    "⏱️",
    "⏲️",
    "⏰",
    "🕰️",
    "⌛",
    "⏳",
    "📡",
    "🔋",
    "🔌",
    "💡",
    "🔦",
    "🕯️",
    "🧯",
    "🛢️",
    "💸",
    "💵",
    "💴",
    "💶",
    "💷",
    "💰",
    "💳",
    "💎",
    "⚖️",
    "🛠️",
    "🔨",
    "⚒️",
    "🔧",
    "🔩",
    "⚙️",
    "🗜️",
    "⚡",
    "💣",
    "🧨",
    "🔫",
    "💈",
    "🔮",
    "🧿",
    "📿",
    "🧸",
    "🎈",
    "🎉",
    "🎊",
    "🎁",
    "🎀",
    "🎗️",
    "🏆",
    "🥇",
    "🥈",
    "🥉",
  ],
  Symbols: [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🖤",
    "🤍",
    "🤎",
    "💔",
    "❣️",
    "💕",
    "💞",
    "💓",
    "💗",
    "💖",
    "💘",
    "💝",
    "💟",
    "☮️",
    "✝️",
    "☪️",
    "🕉️",
    "☸️",
    "✡️",
    "🔯",
    "🕎",
    "☯️",
    "☦️",
    "🛐",
    "⛎",
    "♈",
    "♉",
    "♊",
    "♋",
    "♌",
    "♍",
    "♎",
    "♏",
    "♐",
    "♑",
    "♒",
    "♓",
    "🆔",
    "⚛️",
    "🉑",
    "☢️",
    "☣️",
    "📴",
    "📳",
    "🈶",
    "🈚",
    "🈸",
    "🈺",
    "🈷️",
    "✴️",
    "🆚",
    "💮",
    "🉐",
    "㊙️",
    "㊗️",
    "🈴",
    "🈵",
    "🈹",
    "🈲",
    "🅰️",
    "🅱️",
    "🆎",
    "🆑",
    "🅾️",
    "🆘",
    "❌",
    "⭕",
    "🛑",
    "⛔",
    "📛",
    "🚫",
    "💯",
    "💢",
    "♨️",
    "🚷",
    "🚯",
    "🚳",
    "🚱",
    "🔞",
    "📵",
    "🚭",
    "❗",
    "❓",
    "❕",
    "❔",
    "‼️",
    "⁉️",
    "🔅",
    "🔆",
    "〽️",
    "⚠️",
    "🚸",
    "🔱",
    "⚜️",
    "🔰",
    "♻️",
    "✅",
    "🈯",
    "💹",
    "❇️",
    "✳️",
    "❎",
    "🌐",
    "💠",
    "Ⓜ️",
    "🌀",
    "💤",
    "🏧",
    "🚾",
    "♿",
    "🅿️",
    "🈳",
    "🈂️",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "🚹",
    "🚺",
    "🚼",
    "🚻",
    "🚮",
    "🎦",
    "📶",
    "🈁",
    "🔣",
    "ℹ️",
    "🔤",
    "🔡",
    "🔠",
    "🔢",
    "🔟",
    "🔜",
    "🔝",
    "🔛",
    "🔚",
    "🔙",
    "⏩",
    "⏪",
    "⏫",
    "⏬",
    "◀️",
    "▶️",
    "🔼",
    "🔽",
    "➡️",
    "⬅️",
    "⬆️",
    "⬇️",
    "↗️",
    "↘️",
    "↙️",
    "↖️",
    "↕️",
    "↔️",
    "↪️",
    "↩️",
    "⤴️",
    "⤵️",
    "🔀",
    "🔁",
    "🔂",
    "🔃",
    "🔄",
    "🎵",
    "🎶",
    "➕",
    "➖",
    "➗",
    "✖️",
    "💲",
    "💱",
    "™️",
    "©️",
    "®️",
    "〰️",
    "➰",
    "➿",
    "✔️",
    "☑️",
    "🔘",
    "⚪",
    "⚫",
    "🔴",
    "🔵",
    "🟤",
    "🟡",
    "🟢",
    "🟠",
    "🟣",
    "🔺",
    "🔻",
    "🔸",
    "🔹",
    "🔶",
    "🔷",
    "🔳",
    "🔲",
    "▪️",
    "▫️",
    "◾",
    "◽",
    "◼️",
    "◻️",
    "🟥",
    "🟧",
    "🟨",
    "🟩",
    "🟦",
    "🟪",
    "🟫",
    "⬛",
    "⬜",
    "🔈",
    "🔇",
    "🔉",
    "🔊",
    "🔔",
    "🔕",
    "📣",
    "📢",
    "💬",
    "💭",
    "🗯️",
    "♠️",
    "♣️",
    "♥️",
    "♦️",
    "🃏",
    "🎴",
    "🀄",
    "🕐",
    "🕑",
    "🕒",
    "🕓",
    "🕔",
    "🕕",
    "🕖",
    "🕗",
    "🕘",
    "🕙",
    "🕚",
    "🕛",
  ],
};

// Mapping of emojis to their searchable names/keywords
export const emojiNames: Record<string, string[]> = {
  // Smileys & People
  "😀": ["grinning", "happy", "smile", "face"],
  "😃": ["grinning", "happy", "smile", "big", "eyes"],
  "😄": ["grinning", "happy", "smile", "eyes", "joy"],
  "😁": ["beaming", "happy", "smile", "eyes"],
  "😆": ["grinning", "squinting", "happy", "laugh"],
  "😅": ["grinning", "sweat", "happy", "nervous"],
  "😂": ["laughing", "tears", "joy", "happy", "cry"],
  "🤣": ["rolling", "laughing", "floor", "funny", "laugh"],
  "😊": ["smiling", "eyes", "happy", "blush"],
  "😇": ["smiling", "halo", "angel", "innocent"],
  "🙂": ["slightly", "smiling", "happy"],
  "🙃": ["upside", "down", "face", "silly"],
  "😉": ["winking", "eye", "flirt", "wink"],
  "😌": ["relieved", "calm", "peaceful"],
  "😍": ["heart", "eyes", "love", "adore"],
  "🥰": ["smiling", "hearts", "love", "adore"],
  "😘": ["kissing", "heart", "love", "kiss"],
  "😗": ["kissing", "love"],
  "😙": ["kissing", "smiling", "eyes"],
  "😚": ["kissing", "closed", "eyes"],
  "😋": ["savoring", "food", "yum", "delicious"],
  "😛": ["tongue", "silly", "playful"],
  "😝": ["squinting", "tongue", "silly"],
  "😜": ["winking", "tongue", "silly"],
  "🤪": ["zany", "crazy", "wild"],
  "🤨": ["raised", "eyebrow", "suspicious"],
  "🧐": ["monocle", "thinking", "smart"],
  "🤓": ["nerd", "glasses", "smart", "geek"],
  "😎": ["smiling", "sunglasses", "cool"],
  "🤩": ["star", "eyes", "excited"],
  "🥳": ["partying", "celebration", "party"],
  "😏": ["smirking", "smug"],
  "😒": ["unamused", "bored"],
  "😞": ["disappointed", "sad"],
  "😔": ["pensive", "sad"],
  "😟": ["worried", "concerned"],
  "😕": ["slightly", "frowning", "sad"],
  "🙁": ["frowning", "sad"],
  "☹️": ["frowning", "sad"],
  "😣": ["persevering", "struggling"],
  "😖": ["confounded", "frustrated"],
  "😫": ["tired", "exhausted"],
  "😩": ["weary", "tired"],
  "🥺": ["pleading", "puppy", "eyes", "sad"],
  "😢": ["crying", "tears", "sad"],
  "😭": ["loudly", "crying", "tears", "sad"],
  "😤": ["triumph", "proud"],
  "😠": ["angry", "mad"],
  "😡": ["pouting", "angry", "mad"],
  "🤬": ["swearing", "cursing", "angry"],
  "🤯": ["exploding", "head", "mind", "blown"],
  "😳": ["flushed", "embarrassed", "blush"],
  "🥵": ["hot", "sweating"],
  "🥶": ["cold", "freezing"],
  "😱": ["screaming", "fear", "scared"],
  "😨": ["fearful", "scared"],
  "😰": ["anxious", "sweat", "nervous"],
  "😥": ["sad", "relieved", "sweat"],
  "😓": ["downcast", "sweat", "sad"],
  "🤗": ["hugging", "hug", "love"],
  "🤔": ["thinking", "thought"],
  "🤭": ["hand", "mouth", "shush", "secret"],
  "🤫": ["shushing", "quiet", "secret"],
  "🤥": ["lying", "liar", "nose"],
  "😶": ["mute", "silent", "no", "mouth"],
  "😐": ["neutral", "face"],
  "😑": ["expressionless", "blank"],
  "😬": ["grimacing", "awkward"],
  "🙄": ["rolling", "eyes", "sarcastic"],
  "😯": ["hushed", "surprised"],
  "😦": ["frowning", "open", "mouth"],
  "😧": ["anguished", "pain"],
  "😮": ["open", "mouth", "surprised"],
  "😲": ["astonished", "surprised"],
  "🥱": ["yawning", "tired", "sleepy"],
  "😴": ["sleeping", "tired", "sleep"],
  "🤤": ["drooling", "hungry"],
  "😪": ["sleepy", "tired", "sleep"],
  "😵": ["dizzy", "confused"],
  "🤐": ["zipper", "mouth", "silent"],
  "🥴": ["woozy", "dizzy", "drunk"],
  "🤢": ["nauseated", "sick", "vomit"],
  "🤮": ["vomiting", "sick", "vomit"],
  "🤧": ["sneezing", "sick"],
  "😷": ["mask", "sick", "medical"],
  "🤒": ["thermometer", "sick", "fever"],
  "🤕": ["bandage", "injured", "hurt"],
  "🤑": ["money", "mouth", "rich", "greedy"],
  "🤠": ["cowboy", "hat", "western"],
  "😈": ["smiling", "devil", "evil", "horn"],
  "👿": ["angry", "devil", "evil", "horn"],
  "👹": ["ogre", "monster", "japanese"],
  "👺": ["goblin", "monster", "japanese"],
  "🤡": ["clown", "funny", "circus"],
  "💩": ["poop", "poo", "shit", "smile"],
  "👻": ["ghost", "spooky", "halloween"],
  "💀": ["skull", "death", "dead"],
  "☠️": ["skull", "crossbones", "death", "pirate"],
  "👽": ["alien", "ufo", "space"],
  "👾": ["alien", "monster", "game", "arcade"],
  "🤖": ["robot", "bot", "machine"],
  "🎃": ["jack", "lantern", "halloween", "pumpkin"],
  "😺": ["grinning", "cat", "smile"],
  "😸": ["grinning", "cat", "eyes", "happy"],
  "😹": ["cat", "tears", "joy", "laugh"],
  "😻": ["heart", "eyes", "cat", "love"],
  "😼": ["winking", "cat", "wink"],
  "😽": ["kissing", "cat", "kiss"],
  "🙀": ["weary", "cat", "surprised"],
  "😿": ["crying", "cat", "tears", "sad"],
  "😾": ["pouting", "cat", "angry"],

  // Animals & Nature
  "🐶": ["dog", "puppy", "pet"],
  "🐱": ["cat", "kitten", "pet"],
  "🐭": ["mouse", "rodent"],
  "🐹": ["hamster", "pet", "rodent"],
  "🐰": ["rabbit", "bunny", "bun"],
  "🦊": ["fox", "animal"],
  "🐻": ["bear", "animal"],
  "🐼": ["panda", "bear", "china"],
  "🐨": ["koala", "australia", "bear"],
  "🐯": ["tiger", "cat", "animal"],
  "🦁": ["lion", "king", "animal"],
  "🐮": ["cow", "animal", "milk"],
  "🐷": ["pig", "animal"],
  "🐽": ["pig", "nose", "snout"],
  "🐸": ["frog", "animal", "green"],
  "🐵": ["monkey", "animal"],
  "🙈": ["see", "no", "evil", "monkey"],
  "🙉": ["hear", "no", "evil", "monkey"],
  "🙊": ["speak", "no", "evil", "monkey"],
  "🐒": ["monkey", "animal"],
  "🐔": ["chicken", "bird", "rooster"],
  "🐧": ["penguin", "bird", "cold"],
  "🐦": ["bird", "flying"],
  "🐤": ["baby", "chick", "bird"],
  "🐣": ["hatching", "chick", "bird"],
  "🐥": ["front", "facing", "chick", "bird"],
  "🦆": ["duck", "bird", "water"],
  "🦅": ["eagle", "bird", "flying"],
  "🦉": ["owl", "bird", "wise"],
  "🦇": ["bat", "animal", "halloween"],
  "🐺": ["wolf", "animal"],
  "🐗": ["boar", "pig", "animal"],
  "🐴": ["horse", "animal"],
  "🦄": ["unicorn", "magic", "fantasy"],
  "🐝": ["bee", "honey", "insect"],
  "🐛": ["bug", "insect", "caterpillar"],
  "🦋": ["butterfly", "insect", "beautiful"],
  "🐌": ["snail", "slow", "shell"],
  "🐞": ["ladybug", "insect", "red"],
  "🐜": ["ant", "insect"],
  "🦟": ["mosquito", "insect", "bite"],
  "🦗": ["cricket", "insect"],
  "🕷️": ["spider", "web", "insect"],
  "🦂": ["scorpion", "insect", "sting"],
  "🐢": ["turtle", "slow", "shell"],
  "🐍": ["snake", "reptile"],
  "🦎": ["lizard", "reptile"],
  "🦖": ["t-rex", "dinosaur", "rex"],
  "🦕": ["sauropod", "dinosaur"],
  "🐙": ["octopus", "sea", "tentacles"],
  "🦑": ["squid", "sea", "ocean"],
  "🦐": ["shrimp", "seafood"],
  "🦞": ["lobster", "seafood"],
  "🦀": ["crab", "seafood", "claws"],
  "🐡": ["blowfish", "fish", "puffer"],
  "🐠": ["tropical", "fish", "ocean"],
  "🐟": ["fish", "ocean", "water"],
  "🐬": ["dolphin", "ocean", "smart"],
  "🐳": ["spouting", "whale", "ocean"],
  "🐋": ["whale", "ocean", "big"],
  "🦈": ["shark", "ocean", "danger"],
  "🐊": ["crocodile", "alligator", "reptile"],
  "🐅": ["tiger", "animal", "stripes"],
  "🐆": ["leopard", "animal", "spots"],
  "🦓": ["zebra", "animal", "stripes"],
  "🦍": ["gorilla", "ape", "animal"],
  "🦧": ["orangutan", "ape", "animal"],
  "🐘": ["elephant", "animal", "big"],
  "🦛": ["hippopotamus", "hippo", "animal"],
  "🦏": ["rhinoceros", "rhino", "animal"],
  "🐪": ["camel", "desert", "hump"],
  "🐫": ["two", "hump", "camel", "desert"],
  "🦒": ["giraffe", "animal", "tall", "neck"],
  "🦘": ["kangaroo", "australia", "pouch"],
  "🦡": ["badger", "animal"],
  "🐃": ["water", "buffalo", "animal"],
  "🐂": ["ox", "bull", "animal"],
  "🐄": ["cow", "animal", "milk"],
  "🐎": ["horse", "racing", "animal"],
  "🐖": ["pig", "animal"],
  "🐏": ["ram", "sheep", "animal"],
  "🐑": ["sheep", "wool", "animal"],
  "🦙": ["llama", "alpaca", "animal"],
  "🐐": ["goat", "animal"],
  "🦌": ["deer", "animal", "antlers"],

  // Food & Drink
  "🍏": ["green", "apple", "fruit"],
  "🍎": ["red", "apple", "fruit"],
  "🍐": ["pear", "fruit"],
  "🍊": ["orange", "tangerine", "fruit"],
  "🍋": ["lemon", "fruit", "sour"],
  "🍌": ["banana", "fruit"],
  "🍉": ["watermelon", "fruit", "summer"],
  "🍇": ["grapes", "fruit", "wine"],
  "🍓": ["strawberry", "fruit", "red"],
  "🍈": ["melon", "fruit"],
  "🍒": ["cherries", "fruit", "red"],
  "🍑": ["peach", "fruit"],
  "🥭": ["mango", "fruit", "tropical"],
  "🍍": ["pineapple", "fruit", "tropical"],
  "🥥": ["coconut", "fruit", "tropical"],
  "🥝": ["kiwi", "fruit", "green"],
  "🍅": ["tomato", "vegetable", "red"],
  "🍆": ["eggplant", "vegetable", "purple"],
  "🥑": ["avocado", "vegetable", "green"],
  "🥦": ["broccoli", "vegetable", "green"],
  "🥬": ["leafy", "green", "vegetable"],
  "🥒": ["cucumber", "vegetable", "green"],
  "🌶️": ["hot", "pepper", "spicy", "chili"],
  "🌽": ["corn", "maize", "vegetable"],
  "🥕": ["carrot", "vegetable", "orange"],
  "🥔": ["potato", "vegetable"],
  "🍠": ["sweet", "potato", "yam"],
  "🥐": ["croissant", "bread", "french"],
  "🥯": ["bagel", "bread"],
  "🍞": ["bread", "loaf"],
  "🥖": ["baguette", "bread", "french"],
  "🥨": ["pretzel", "bread", "twisted"],
  "🧀": ["cheese", "dairy"],
  "🥚": ["egg", "food"],
  "🍳": ["cooking", "fried", "egg", "pan"],
  "🥞": ["pancakes", "breakfast", "stack"],
  "🥓": ["bacon", "meat", "breakfast"],
  "🥩": ["meat", "steak", "beef"],
  "🍗": ["poultry", "leg", "chicken", "drumstick"],
  "🍖": ["meat", "bone"],
  "🦴": ["bone", "skeleton"],
  "🌭": ["hot", "dog", "sausage"],
  "🍔": ["hamburger", "burger", "fast", "food"],
  "🍟": ["french", "fries", "potato"],
  "🍕": ["pizza", "slice", "cheese"],
  "🥪": ["sandwich", "bread"],
  "🥙": ["stuffed", "flatbread", "wrap"],
  "🌮": ["taco", "mexican", "food"],
  "🌯": ["burrito", "mexican", "wrap"],
  "🥗": ["green", "salad", "healthy"],
  "🥘": ["shallow", "pan", "food", "paella"],
  "🥫": ["canned", "food", "can"],
  "🍝": ["spaghetti", "pasta", "italian"],
  "🍜": ["steaming", "bowl", "noodles", "ramen"],
  "🍲": ["pot", "food", "stew"],
  "🍛": ["curry", "rice", "indian"],
  "🍣": ["sushi", "japanese", "fish"],
  "🍱": ["bento", "box", "japanese", "lunch"],
  "🥟": ["dumpling", "chinese"],
  "🍤": ["fried", "shrimp", "tempura"],
  "🍙": ["rice", "ball", "japanese"],
  "🍚": ["cooked", "rice"],
  "🍘": ["rice", "cracker"],
  "🍥": ["fish", "cake", "swirl"],
  "🥠": ["fortune", "cookie", "chinese"],
  "🍢": ["oden", "skewer", "japanese"],
  "🍡": ["dango", "sweet", "japanese"],
  "🍧": ["shaved", "ice", "dessert"],
  "🍨": ["ice", "cream", "dessert"],
  "🍦": ["soft", "ice", "cream", "dessert"],
  "🥧": ["pie", "dessert"],
  "🍰": ["birthday", "cake", "dessert"],
  "🎂": ["birthday", "cake", "candles"],
  "🍮": ["custard", "pudding", "dessert"],
  "🍭": ["lollipop", "candy", "sweet"],
  "🍬": ["candy", "sweet"],
  "🍫": ["chocolate", "bar", "sweet"],
  "🍿": ["popcorn", "movie", "snack"],
  "🍩": ["doughnut", "donut", "sweet"],
  "🍪": ["cookie", "biscuit", "sweet"],
  "🌰": ["chestnut", "nut"],
  "🥜": ["peanuts", "nuts"],
  "🍯": ["honey", "pot", "sweet"],
  "🥛": ["glass", "milk", "drink"],
  "🍼": ["baby", "bottle", "milk"],
  "☕": ["hot", "beverage", "coffee", "tea"],
  "🍵": ["teacup", "tea", "green"],
  "🥤": ["cup", "straw", "drink", "soda"],
  "🍶": ["sake", "bottle", "cup", "japanese"],
  "🍺": ["beer", "mug", "drink", "alcohol"],
  "🍻": ["clinking", "beer", "mugs", "cheers"],
  "🥂": ["clinking", "glasses", "champagne", "cheers"],
  "🍷": ["wine", "glass", "drink", "alcohol"],
  "🥃": ["tumbler", "glass", "whiskey", "drink"],
  "🍸": ["cocktail", "glass", "drink"],
  "🍹": ["tropical", "drink", "cocktail"],
  "🧃": ["beverage", "box", "juice"],
  "🧉": ["mate", "drink", "tea"],
  "🧊": ["ice", "cube", "cold"],
  "🥄": ["spoon", "utensil"],
  "🍴": ["fork", "knife", "utensils"],
  "🍽️": ["fork", "knife", "plate", "dining"],
  "🥣": ["bowl", "spoon", "soup"],
  "🥡": ["takeout", "box", "chinese"],
  "🥢": ["chopsticks", "utensils", "asian"],
  "🧂": ["salt", "shaker", "seasoning"],

  // Activity & Sports
  "⚽": ["soccer", "football", "ball", "sport"],
  "🏀": ["basketball", "ball", "sport"],
  "🏈": ["american", "football", "sport"],
  "⚾": ["baseball", "ball", "sport"],
  "🥎": ["softball", "ball", "sport"],
  "🎾": ["tennis", "ball", "racket", "sport"],
  "🏐": ["volleyball", "ball", "sport"],
  "🏉": ["rugby", "football", "sport"],
  "🥏": ["flying", "disc", "frisbee", "sport"],
  "🎱": ["pool", "8", "ball", "billiards"],
  "🏓": ["ping", "pong", "table", "tennis"],
  "🏸": ["badminton", "racket", "sport"],
  "🥅": ["goal", "net", "hockey"],
  "🏒": ["ice", "hockey", "stick", "puck"],
  "🏑": ["field", "hockey", "stick"],
  "🏏": ["cricket", "bat", "ball"],
  "🥍": ["lacrosse", "stick", "ball"],
  "🏹": ["bow", "arrow", "archery"],
  "🎣": ["fishing", "pole", "fish"],
  "🥊": ["boxing", "glove", "punch"],
  "🥋": ["martial", "arts", "uniform", "karate"],
  "🎽": ["running", "shirt", "marathon"],
  "🛹": ["skateboard", "skating"],
  "🛷": ["sled", "sledge", "snow"],
  "⛸️": ["ice", "skate", "skating"],
  "🥌": ["curling", "stone", "sport"],
  "🎿": ["skis", "skiing", "snow"],
  "⛷️": ["skier", "skiing", "snow"],
  "🏂": ["snowboarder", "snowboarding"],
  "🏋️": ["weight", "lifter", "gym", "fitness"],
  "🤼": ["wrestlers", "wrestling", "sport"],
  "🤸": ["person", "cartwheeling", "gymnastics"],
  "🤺": ["fencer", "fencing", "sword"],
  "⛹️": ["person", "bouncing", "ball", "basketball"],
  "🤾": ["handball", "sport"],
  "🏌️": ["golfer", "golf", "club"],
  "🏇": ["horse", "racing", "jockey"],
  "🧘": ["person", "lotus", "position", "yoga", "meditation"],
  "🏄": ["surfer", "surfing", "wave"],
  "🏊": ["swimmer", "swimming", "water"],
  "🚣": ["rowboat", "rowing", "water"],
  "🧗": ["climber", "climbing", "mountain"],
  "🚵": ["mountain", "bicyclist", "biking"],
  "🚴": ["bicyclist", "cycling", "bike"],
  "🏆": ["trophy", "award", "winner", "prize"],
  "🥇": ["1st", "place", "medal", "gold", "winner"],
  "🥈": ["2nd", "place", "medal", "silver"],
  "🥉": ["3rd", "place", "medal", "bronze"],
  "🏅": ["sports", "medal", "award"],
  "🎖️": ["military", "medal", "award"],
  "🏵️": ["rosette", "medal", "award"],
  "🎗️": ["reminder", "ribbon", "awareness"],
  "🎫": ["ticket", "admission"],
  "🎟️": ["admission", "tickets", "entrance"],
  "🎪": ["circus", "tent", "entertainment"],
  "🤹": ["juggling", "juggler", "circus"],
  "🎭": ["performing", "arts", "theater", "drama"],
  "🩰": ["ballet", "shoes", "dance"],
  "🎨": ["artist", "palette", "paint", "art"],
  "🎬": ["clapper", "board", "movie", "film"],
  "🎤": ["microphone", "sing", "karaoke", "music"],
  "🎧": ["headphone", "music", "listen"],
  "🎼": ["musical", "score", "sheet", "music"],
  "🎹": ["piano", "keyboard", "music"],
  "🥁": ["drum", "music", "beat"],
  "🎷": ["saxophone", "music", "jazz"],
  "🎺": ["trumpet", "music", "brass"],
  "🎸": ["guitar", "music", "rock"],
  "🎻": ["violin", "music", "classical"],
  "🎲": ["game", "die", "dice", "gambling"],
  "♟️": ["chess", "pawn", "game"],
  "🎯": ["direct", "hit", "target", "dart"],
  "🎳": ["bowling", "ball", "pin"],
  "🎮": ["video", "game", "controller", "gaming"],
  "🎰": ["slot", "machine", "casino", "gambling"],
  "🧩": ["puzzle", "piece", "jigsaw"],

  // Travel & Places
  "🚗": ["car", "automobile", "vehicle"],
  "🚕": ["taxi", "cab", "vehicle"],
  "🚙": ["suv", "sport", "utility", "vehicle"],
  "🚌": ["bus", "public", "transport"],
  "🚎": ["trolleybus", "bus", "electric"],
  "🏎️": ["racing", "car", "speed"],
  "🚓": ["police", "car", "cop"],
  "🚑": ["ambulance", "medical", "emergency"],
  "🚒": ["fire", "engine", "truck", "firefighter"],
  "🚐": ["minibus", "van"],
  "🚚": ["delivery", "truck", "van"],
  "🚛": ["articulated", "lorry", "truck"],
  "🚜": ["tractor", "farm"],
  "🛴": ["scooter", "kick"],
  "🚲": ["bicycle", "bike", "cycling"],
  "🛵": ["motor", "scooter", "vespa"],
  "🏍️": ["motorcycle", "bike"],
  "🛺": ["auto", "rickshaw", "tuk", "tuk"],
  "🚨": ["police", "car", "light", "siren"],
  "🚔": ["oncoming", "police", "car"],
  "🚍": ["oncoming", "bus"],
  "🚘": ["oncoming", "automobile", "car"],
  "🚖": ["oncoming", "taxi"],
  "🚡": ["aerial", "tramway", "cable", "car"],
  "🚠": ["mountain", "cableway", "gondola"],
  "🚟": ["suspension", "railway"],
  "🚃": ["tram", "car", "trolley"],
  "🚋": ["tram", "car"],
  "🚞": ["mountain", "railway"],
  "🚝": ["monorail"],
  "🚄": ["high", "speed", "train", "bullet"],
  "🚅": ["bullet", "train", "shinkansen"],
  "🚈": ["light", "rail"],
  "🚂": ["locomotive", "steam", "train"],
  "🚆": ["train", "railway"],
  "🚇": ["metro", "subway", "underground"],
  "🚊": ["tram"],
  "🚉": ["station", "train"],
  "✈️": ["airplane", "flight", "airplane"],
  "🛫": ["airplane", "departure"],
  "🛬": ["airplane", "arrival"],
  "🛩️": ["small", "airplane"],
  "💺": ["seat", "chair", "airplane"],
  "🚀": ["rocket", "space", "launch"],
  "🛸": ["flying", "saucer", "ufo", "alien"],
  "🚁": ["helicopter", "chopper"],
  "🛶": ["canoe", "kayak", "boat"],
  "⛵": ["sailboat", "sailing", "boat"],
  "🚤": ["speedboat", "boat", "fast"],
  "🛥️": ["motor", "boat"],
  "🛳️": ["passenger", "ship", "cruise"],
  "⛴️": ["ferry", "boat"],
  "🚢": ["ship", "boat", "cruise"],
  "⚓": ["anchor", "ship", "boat"],
  "⛽": ["fuel", "pump", "gas", "station"],
  "🚧": ["construction", "barrier", "roadwork"],
  "🚦": ["vertical", "traffic", "light"],
  "🚥": ["horizontal", "traffic", "light"],
  "🗺️": ["world", "map", "globe"],
  "🗿": ["moai", "easter", "island", "statue"],
  "🗽": ["statue", "liberty", "new", "york"],
  "🗼": ["tokyo", "tower", "japan"],
  "🏰": ["castle", "european"],
  "🏯": ["japanese", "castle"],
  "🏟️": ["stadium", "sports", "arena"],
  "🎡": ["ferris", "wheel", "amusement"],
  "🎢": ["roller", "coaster", "amusement"],
  "🎠": ["carousel", "horse", "merry", "go", "round"],
  "⛲": ["fountain", "water"],
  "⛱️": ["umbrella", "beach", "sun"],
  "🏖️": ["beach", "umbrella", "sand"],
  "🏝️": ["desert", "island"],
  "🏜️": ["desert", "sand"],
  "🌋": ["volcano", "eruption", "lava"],
  "⛰️": ["mountain", "peak"],
  "🏔️": ["snow", "capped", "mountain"],
  "🗻": ["mount", "fuji", "japan"],
  "🏕️": ["camping", "tent"],
  "⛺": ["tent", "camping"],
  "🏠": ["house", "home"],
  "🏡": ["house", "garden", "home"],
  "🏘️": ["houses", "neighborhood"],
  "🏚️": ["derelict", "house", "abandoned"],
  "🏗️": ["building", "construction"],
  "🏭": ["factory", "industrial"],
  "🏢": ["office", "building", "skyscraper"],
  "🏬": ["department", "store", "shopping"],
  "🏣": ["japanese", "post", "office"],
  "🏤": ["european", "post", "office"],
  "🏥": ["hospital", "medical"],
  "🏦": ["bank", "money"],
  "🏨": ["hotel", "accommodation"],
  "🏪": ["convenience", "store", "shop"],
  "🏫": ["school", "education"],
  "🏩": ["love", "hotel", "romantic"],
  "💒": ["wedding", "chapel", "marriage"],
  "🏛️": ["classical", "building", "temple"],
  "⛪": ["church", "christian", "religion"],
  "🕌": ["mosque", "islam", "religion"],
  "🕍": ["synagogue", "jewish", "religion"],
  "🕋": ["kaaba", "mecca", "islam"],
  "⛩️": ["shinto", "shrine", "japan"],
  "🛤️": ["railway", "track", "train"],
  "🛣️": ["motorway", "highway", "road"],
  "🗾": ["map", "japan", "japanese"],
  "🎑": ["moon", "viewing", "ceremony", "japan"],
  "🏞️": ["national", "park", "nature"],
  "🌅": ["sunrise", "morning", "sun"],
  "🌄": ["sunrise", "mountains", "morning"],
  "🌠": ["shooting", "star", "wish"],
  "🎇": ["sparkler", "fireworks"],
  "🎆": ["fireworks", "celebration"],
  "🌇": ["cityscape", "dusk", "sunset"],
  "🌆": ["cityscape", "dusk", "buildings"],
  "🏙️": ["cityscape", "skyline", "urban"],
  "🌃": ["night", "cityscape", "stars"],
  "🌌": ["milky", "way", "space", "stars"],
  "🌉": ["bridge", "night", "city"],
  "🌁": ["foggy", "fog", "cloudy"],

  // Objects
  "⌚": ["watch", "time", "clock"],
  "📱": ["mobile", "phone", "smartphone"],
  "📲": ["mobile", "phone", "arrow", "call"],
  "💻": ["laptop", "computer"],
  "⌨️": ["keyboard", "computer", "type"],
  "🖥️": ["desktop", "computer", "monitor"],
  "🖨️": ["printer", "computer"],
  "🖱️": ["computer", "mouse"],
  "🖲️": ["trackball", "computer"],
  "🕹️": ["joystick", "game", "controller"],
  "🗜️": ["clamp", "compression"],
  "💾": ["floppy", "disk", "save"],
  "💿": ["optical", "disk", "cd", "dvd"],
  "📀": ["dvd", "disk"],
  "📼": ["videocassette", "tape", "vhs"],
  "📷": ["camera", "photo"],
  "📸": ["camera", "flash", "photo"],
  "📹": ["video", "camera", "recording"],
  "🎥": ["movie", "camera", "film"],
  "📽️": ["film", "projector", "movie"],
  "🎞️": ["film", "frames", "movie"],
  "📞": ["telephone", "receiver", "call"],
  "☎️": ["telephone", "phone", "call"],
  "📟": ["pager", "beeper"],
  "📠": ["fax", "machine"],
  "📺": ["television", "tv"],
  "📻": ["radio", "music"],
  "🎙️": ["studio", "microphone", "recording"],
  "🎚️": ["level", "slider", "control"],
  "🎛️": ["control", "knobs", "audio"],
  "⏱️": ["stopwatch", "time"],
  "⏲️": ["timer", "clock", "time"],
  "⏰": ["alarm", "clock", "wake"],
  "🕰️": ["mantelpiece", "clock", "time"],
  "⌛": ["hourglass", "done", "time"],
  "⏳": ["hourglass", "not", "done", "time"],
  "📡": ["satellite", "antenna", "signal"],
  "🔋": ["battery", "power", "energy"],
  "🔌": ["electric", "plug", "power"],
  "💡": ["light", "bulb", "idea"],
  "🔦": ["flashlight", "torch", "light"],
  "🕯️": ["candle", "light"],
  "🧯": ["fire", "extinguisher", "safety"],
  "🛢️": ["oil", "drum", "barrel"],
  "💸": ["money", "wings", "flying", "dollar"],
  "💵": ["dollar", "banknote", "money"],
  "💴": ["yen", "banknote", "money", "japan"],
  "💶": ["euro", "banknote", "money"],
  "💷": ["pound", "banknote", "money", "uk"],
  "💰": ["money", "bag", "dollar", "rich"],
  "💳": ["credit", "card", "payment"],
  "💎": ["gem", "diamond", "jewel"],
  "⚖️": ["balance", "scale", "justice", "law"],
  "🛠️": ["hammer", "wrench", "tools"],
  "🔨": ["hammer", "tool"],
  "⚒️": ["hammer", "pick", "tools"],
  "🔧": ["wrench", "tool", "repair"],
  "🔩": ["nut", "bolt", "screw"],
  "⚙️": ["gear", "cog", "settings"],
  "⚡": ["high", "voltage", "lightning", "electric"],
  "💣": ["bomb", "explosive", "danger"],
  "🧨": ["firecracker", "explosive", "celebration"],
  "🔫": ["water", "pistol", "gun", "toy"],
  "💈": ["barber", "pole", "haircut"],
  "🔮": ["crystal", "ball", "magic", "fortune"],
  "🧿": ["nazar", "amulet", "evil", "eye"],
  "📿": ["prayer", "beads", "rosary"],
  "🧸": ["teddy", "bear", "toy", "stuffed"],
  "🎈": ["balloon", "party", "celebration"],
  "🎉": ["party", "popper", "celebration"],
  "🎊": ["confetti", "ball", "celebration"],
  "🎁": ["wrapped", "gift", "present"],
  "🎀": ["ribbon", "bow", "decoration"],

  // Symbols
  "❤️": [
    "red",
    "heart",
    "love",
    "mostage",
    "mostafa",
    "farid",
    "omid",
    "jeff",
    "mohsen",
  ],
  "🧡": ["orange", "heart"],
  "💛": ["yellow", "heart"],
  "💚": ["green", "heart"],
  "💙": ["blue", "heart"],
  "💜": ["purple", "heart"],
  "🖤": ["black", "heart"],
  "🤍": ["white", "heart"],
  "🤎": ["brown", "heart"],
  "💔": ["broken", "heart", "sad", "arsham"],
  "❣️": ["heart", "exclamation", "love"],
  "💕": ["two", "hearts", "love"],
  "💞": ["revolving", "hearts", "love"],
  "💓": ["beating", "heart", "love"],
  "💗": ["growing", "heart", "love"],
  "💖": ["sparkling", "heart", "love"],
  "💘": ["cupid", "heart", "love", "arrow"],
  "💝": ["heart", "ribbon", "gift", "love"],
  "💟": ["heart", "decoration", "love"],
  "☮️": ["peace", "symbol"],
  "✝️": ["latin", "cross", "christian"],
  "☪️": ["star", "crescent", "islam"],
  "🕉️": ["om", "hindu", "symbol"],
  "☸️": ["wheel", "dharma", "buddhism"],
  "✡️": ["star", "david", "jewish"],
  "🔯": ["dotted", "six", "pointed", "star"],
  "🕎": ["menorah", "jewish", "hanukkah"],
  "☯️": ["yin", "yang", "taoism"],
  "☦️": ["orthodox", "cross", "christian"],
  "🛐": ["place", "worship", "religion"],
  "⛎": ["ophiuchus", "zodiac"],
  "♈": ["aries", "zodiac", "ram"],
  "♉": ["taurus", "zodiac", "bull"],
  "♊": ["gemini", "zodiac", "twins"],
  "♋": ["cancer", "zodiac", "crab"],
  "♌": ["leo", "zodiac", "lion"],
  "♍": ["virgo", "zodiac"],
  "♎": ["libra", "zodiac", "scales"],
  "♏": ["scorpio", "zodiac", "scorpion"],
  "♐": ["sagittarius", "zodiac", "archer"],
  "♑": ["capricorn", "zodiac", "goat"],
  "♒": ["aquarius", "zodiac", "water", "bearer"],
  "♓": ["pisces", "zodiac", "fish"],
  "🆔": ["identification", "card", "id"],
  "⚛️": ["atom", "symbol", "science"],
  "🉑": ["acceptable", "chinese", "yes"],
  "☢️": ["radioactive", "nuclear", "danger"],
  "☣️": ["biohazard", "danger", "toxic"],
  "📴": ["mobile", "phone", "off"],
  "📳": ["vibration", "mode", "phone"],
  "🈶": ["not", "free", "charge", "japanese"],
  "🈚": ["free", "charge", "japanese"],
  "🈸": ["application", "japanese"],
  "🈺": ["open", "business", "japanese"],
  "🈷️": ["monthly", "amount", "japanese"],
  "✴️": ["eight", "pointed", "star"],
  "🆚": ["vs", "versus", "against"],
  "💮": ["white", "flower", "japanese"],
  "🉐": ["bargain", "japanese"],
  "㊙️": ["secret", "japanese"],
  "㊗️": ["congratulations", "japanese"],
  "🈴": ["passing", "grade", "japanese"],
  "🈵": ["no", "vacancy", "japanese"],
  "🈹": ["discount", "japanese"],
  "🈲": ["prohibited", "japanese"],
  "🅰️": ["a", "button", "blood", "type"],
  "🅱️": ["b", "button", "blood", "type"],
  "🆎": ["ab", "button", "blood", "type"],
  "🆑": ["cl", "button", "clear"],
  "🅾️": ["o", "button", "blood", "type"],
  "🆘": ["sos", "help", "emergency"],
  "❌": ["cross", "mark", "wrong", "no"],
  "⭕": ["heavy", "large", "circle", "yes"],
  "🛑": ["stop", "sign", "octagon"],
  "⛔": ["no", "entry", "prohibited"],
  "📛": ["name", "badge", "identification"],
  "🚫": ["prohibited", "no", "entry"],
  "💯": ["hundred", "points", "perfect", "score"],
  "💢": ["anger", "symbol", "mad"],
  "♨️": ["hot", "springs", "onsen"],
  "🚷": ["no", "pedestrians", "prohibited"],
  "🚯": ["no", "littering", "prohibited"],
  "🚳": ["no", "bicycles", "prohibited"],
  "🚱": ["non", "potable", "water", "prohibited"],
  "🔞": ["no", "one", "under", "eighteen", "adult"],
  "📵": ["no", "mobile", "phones", "prohibited"],
  "🚭": ["no", "smoking", "prohibited"],
  "❗": ["exclamation", "mark", "important"],
  "❓": ["question", "mark", "help"],
  "❕": ["white", "exclamation", "mark"],
  "❔": ["white", "question", "mark"],
  "‼️": ["double", "exclamation", "mark"],
  "⁉️": ["exclamation", "question", "mark"],
  "🔅": ["dim", "button", "low", "brightness"],
  "🔆": ["bright", "button", "high", "brightness"],
  "〽️": ["part", "alternation", "mark"],
  "⚠️": ["warning", "caution", "danger"],
  "🚸": ["children", "crossing", "warning"],
  "🔱": ["trident", "emblem", "poseidon"],
  "⚜️": ["fleur", "de", "lis", "france"],
  "🔰": ["japanese", "symbol", "beginner"],
  "♻️": ["recycling", "symbol", "recycle"],
  "✅": ["check", "mark", "button", "yes"],
  "🈯": ["reserved", "japanese"],
  "💹": ["chart", "increasing", "yen", "money"],
  "❇️": ["sparkle", "star"],
  "✳️": ["eight", "spoked", "asterisk"],
  "❎": ["cross", "mark", "button", "no"],
  "🌐": ["globe", "meridians", "world", "internet"],
  "💠": ["diamond", "shape", "dot"],
  "Ⓜ️": ["circled", "m", "metro"],
  "🌀": ["cyclone", "hurricane", "typhoon"],
  "💤": ["zzz", "sleeping", "tired"],
  "🏧": ["atm", "sign", "money", "bank"],
  "🚾": ["water", "closet", "wc", "toilet"],
  "♿": ["wheelchair", "symbol", "accessibility"],
  "🅿️": ["p", "button", "parking"],
  "🈳": ["vacant", "japanese"],
  "🈂️": ["service", "charge", "japanese"],
  "🛂": ["passport", "control", "customs"],
  "🛃": ["customs", "border", "control"],
  "🛄": ["baggage", "claim", "luggage"],
  "🛅": ["left", "luggage", "baggage"],
  "🚹": ["mens", "room", "toilet", "bathroom"],
  "🚺": ["womens", "room", "toilet", "bathroom"],
  "🚼": ["baby", "symbol", "changing"],
  "🚻": ["restroom", "toilet", "bathroom"],
  "🚮": ["litter", "bin", "trash"],
  "🎦": ["cinema", "movie", "theater"],
  "📶": ["antenna", "bars", "signal", "signal"],
  "🈁": ["koko", "japanese", "here"],
  "🔣": ["input", "symbols", "keyboard"],
  ℹ️: ["information", "i", "help"],
  "🔤": ["input", "latin", "letters", "alphabet"],
  "🔡": ["input", "latin", "lowercase", "letters"],
  "🔠": ["input", "latin", "uppercase", "letters"],
  "🔢": ["input", "numbers", "digits"],
  "🔟": ["keycap", "10", "ten"],
  "🔜": ["soon", "arrow", "coming"],
  "🔝": ["top", "arrow", "up"],
  "🔛": ["on", "arrow", "mark"],
  "🔚": ["end", "arrow", "finish"],
  "🔙": ["back", "arrow", "return"],
  "⏩": ["fast", "forward", "double", "arrows"],
  "⏪": ["fast", "reverse", "double", "arrows"],
  "⏫": ["fast", "up", "button", "double", "arrows"],
  "⏬": ["fast", "down", "button", "double", "arrows"],
  "◀️": ["reverse", "button", "left", "arrow"],
  "▶️": ["play", "button", "right", "arrow"],
  "🔼": ["up", "button", "triangle"],
  "🔽": ["down", "button", "triangle"],
  "➡️": ["right", "arrow", "next"],
  "⬅️": ["left", "arrow", "back"],
  "⬆️": ["up", "arrow", "top"],
  "⬇️": ["down", "arrow", "bottom"],
  "↗️": ["up", "right", "arrow", "diagonal"],
  "↘️": ["down", "right", "arrow", "diagonal"],
  "↙️": ["down", "left", "arrow", "diagonal"],
  "↖️": ["up", "left", "arrow", "diagonal"],
  "↕️": ["up", "down", "arrow", "vertical"],
  "↔️": ["left", "right", "arrow", "horizontal"],
  "↪️": ["right", "arrow", "curving", "left"],
  "↩️": ["left", "arrow", "curving", "right"],
  "⤴️": ["right", "arrow", "curving", "up"],
  "⤵️": ["right", "arrow", "curving", "down"],
  "🔀": ["shuffle", "tracks", "button", "random"],
  "🔁": ["repeat", "button", "loop"],
  "🔂": ["repeat", "single", "button", "once"],
  "🔃": ["clockwise", "vertical", "arrows", "refresh"],
  "🔄": ["counterclockwise", "arrows", "button", "refresh"],
  "🎵": ["musical", "note", "music"],
  "🎶": ["musical", "notes", "music"],
  "➕": ["plus", "sign", "add"],
  "➖": ["minus", "sign", "subtract"],
  "➗": ["division", "sign", "divide"],
  "✖️": ["multiplication", "sign", "multiply", "times"],
  "💲": ["heavy", "dollar", "sign", "money"],
  "💱": ["currency", "exchange", "money"],
  "™️": ["trade", "mark", "trademark"],
  "©️": ["copyright", "symbol"],
  "®️": ["registered", "symbol"],
  "〰️": ["wavy", "dash"],
  "➰": ["curly", "loop"],
  "➿": ["double", "curly", "loop"],
  "✔️": ["check", "mark", "yes", "correct"],
  "☑️": ["check", "box", "with", "check", "yes"],
  "🔘": ["radio", "button", "circle"],
  "⚪": ["white", "circle", "button"],
  "⚫": ["black", "circle", "button"],
  "🔴": ["red", "circle", "button"],
  "🔵": ["blue", "circle", "button"],
  "🟤": ["brown", "circle", "button"],
  "🟡": ["yellow", "circle", "button"],
  "🟢": ["green", "circle", "button"],
  "🟠": ["orange", "circle", "button"],
  "🟣": ["purple", "circle", "button"],
  "🔺": ["red", "triangle", "pointed", "up"],
  "🔻": ["red", "triangle", "pointed", "down"],
  "🔸": ["small", "orange", "diamond"],
  "🔹": ["small", "blue", "diamond"],
  "🔶": ["large", "orange", "diamond"],
  "🔷": ["large", "blue", "diamond"],
  "🔳": ["white", "square", "button"],
  "🔲": ["black", "square", "button"],
  "▪️": ["black", "small", "square"],
  "▫️": ["white", "small", "square"],
  "◾": ["black", "medium", "small", "square"],
  "◽": ["white", "medium", "small", "square"],
  "◼️": ["black", "medium", "square"],
  "◻️": ["white", "medium", "square"],
  "🟥": ["red", "square"],
  "🟧": ["orange", "square"],
  "🟨": ["yellow", "square"],
  "🟩": ["green", "square"],
  "🟦": ["blue", "square"],
  "🟪": ["purple", "square"],
  "🟫": ["brown", "square"],
  "⬛": ["black", "large", "square"],
  "⬜": ["white", "large", "square"],
  "🔈": ["speaker", "low", "volume", "sound"],
  "🔇": ["muted", "speaker", "no", "sound"],
  "🔉": ["speaker", "medium", "volume", "sound"],
  "🔊": ["speaker", "high", "volume", "sound"],
  "🔔": ["bell", "notification", "ring"],
  "🔕": ["bell", "with", "slash", "muted", "notification"],
  "📣": ["megaphone", "loudspeaker", "announcement"],
  "📢": ["loudspeaker", "megaphone", "announcement"],
  "💬": ["speech", "balloon", "chat", "talk"],
  "💭": ["thought", "balloon", "think", "bubble"],
  "🗯️": ["right", "anger", "bubble", "mad"],
  "♠️": ["spade", "suit", "card", "poker"],
  "♣️": ["club", "suit", "card", "poker"],
  "♥️": ["heart", "suit", "card", "poker"],
  "♦️": ["diamond", "suit", "card", "poker"],
  "🃏": ["joker", "card", "poker"],
  "🎴": ["flower", "playing", "cards", "japanese"],
  "🀄": ["mahjong", "red", "dragon", "tile"],
  "🕐": ["one", "o", "clock", "1:00"],
  "🕑": ["two", "o", "clock", "2:00"],
  "🕒": ["three", "o", "clock", "3:00"],
  "🕓": ["four", "o", "clock", "4:00"],
  "🕔": ["five", "o", "clock", "5:00"],
  "🕕": ["six", "o", "clock", "6:00"],
  "🕖": ["seven", "o", "clock", "7:00"],
  "🕗": ["eight", "o", "clock", "8:00"],
  "🕘": ["nine", "o", "clock", "9:00"],
  "🕙": ["ten", "o", "clock", "10:00"],
  "🕚": ["eleven", "o", "clock", "11:00"],
  "🕛": ["twelve", "o", "clock", "12:00"],
};
