name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: dropdown
    id: area
    attributes:
      label: Which area is affected?
      description: Which part of the application has the issue?
      options:
        - Editor
        - Presentation Preview
        - Login / Sign Up
        - Import / Export
        - User Dashboard
        - AI Features
        - UI/UX
        - Mostage Library
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What problem are you experiencing?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please list the steps you took that led to this issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: If applicable, add screenshots or images to help explain the problem
      placeholder: Drag and drop images here or paste image URLs

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (Optional)
      description: Any other information you think might be helpful
      placeholder: Add any other context about the problem here...
