name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us better understand your request.

  - type: dropdown
    id: area
    attributes:
      label: Which area does this feature relate to?
      description: Which part of the application would this feature affect?
      options:
        - Editor
        - Presentation Preview
        - Login / Sign Up
        - Import / Export
        - User Dashboard
        - AI Features
        - UI/UX
        - Mostage Library
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Is this feature related to solving a problem? Please describe.
      placeholder: Example: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What feature or improvement would you like?
      placeholder: Describe what you would like to see...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Who would benefit from it?
      placeholder: Describe a specific example or scenario...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples (Optional)
      description: If applicable, add images, mockups, or examples
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Optional)
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (Optional)
      description: Any other information you think might be helpful
      placeholder: Add any other context, screenshots, or examples here...
